// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {main} from '../models';

export function ApplyUpdate():Promise<updater.UpdateProgress>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function GetPlatformInfo():Promise<string>;

export function GetTraySettings():Promise<main.TraySettings>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RestartApp():Promise<void>;

export function SetTraySettings(arg1:main.TraySettings):Promise<void>;
