// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function ApplyUpdate():Promise<updater.UpdateProgress>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function GetPlatformInfo():Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;
